### ISSUE TITLE
Error starting a server

### ISSUE THREAD

**Issue by dzhavat** [TheEvilCorp/OverReact#104]
When I try to run a server I get this error: 

![erro](https://cloud.githubusercontent.com/assets/1096332/12350481/a94037d8-bb77-11e5-9df0-e584f0fbb5f5.png)

**Comment by bgrober** [comment]
Hey,

Usually that issue means that you have something else listening on port 3000. You can try to close any other processes that might be doing that, or you can try to change the port number in the server/server.js; like 8080, 4000, or 5000. If these do not solve the issue, please let us know if you changed the files in anyway, particularly the server file or the grunt file. If they do solve the issue, let us know and we will close this issue. 

Hope it works!
Brian

**Comment by dzhavat** [comment]
Well, this worked out perfectly. Thanks :)

**Comment by bgrober** [comment]
Awesome glad it worked out!!
